### PR TITLE
Use a quicker to run cell in the sscx example to speed up tests

### PR DESCRIPTION
**Pull request by AurelienJaquier**
Also test current values of recipe protocol

When comparing with bglibpy results on the synapse tests, I had to use a longer protocol and raise a little bit the threshold for the tests to pass. The reason is due to, I believe, some rounding error being amplified during the run.

### CODE REVIEW

**Comment by AurelienJaquier** [comment]
With this MR, the tests goes from 18mn to 12mn! \o/

**Comment by wvangeit** [comment]
👍

**Comment by anilbey** [comment]
Sounds very good, let me take some time here since `+38,106 −14,019` is a huge change :)

**Comment by AurelienJaquier** [comment]
Np. The changes are mainly replacing big files, like the morphology, the synapses or test files. Do not fret, the 'reviewable' changes should not be too big.

**Comment by anilbey** [comment]
Ah ok so the same protocol.json files are used with a faster cell.

**Review by anilbey — APPROVED** [review]
Great work. Thanks

**Comment by AurelienJaquier** [comment]
Little note: a changed a cADpyr cell by another cADpyr cell because it has a decay function in the distributions (in config/params/pyr.json). It's good to have that as a test cell to test the handling of the distributions by the factsheets.

**Comment by anilbey** [comment]
I just received this email that the coverage slightly drops on some files but I couldn't see it on the codecov interface. Might that be some edge case uncovered with this new cell?
Screenshot 2021-12-16 at 15 27 58

**Comment by AurelienJaquier** [comment]
Wait, do not merge this yet. I just realized that I was biased when searching for cells. I'll search a little bit deeper, I might find an even quicker cell.

**Comment by AurelienJaquier** [comment]
@anilbey I had the same email, but that's strange. The codecov report here on this MR says that there is no change in coverage, and the link of the email to the full coverage also seems to say the same thing. If we look at each file on coverage, the data does not add up with the ones in the email.
I don't know where the data shown in the email come from.

**Comment by AurelienJaquier** [comment]
I changed the cell, hoping to speed up the tests even more, but we are still at 12mn. However, it increased the coverage a little bit.
@anilbey if you're ok with the new changes, I'll merge this.

**Comment by anilbey** [comment]
Yes sure, go ahead it's ok for me. This cell happens to hit both `if middle_voltage > holding_voltage` and `else` branches during the search for the holding current. That's why there's more coverage.

**Pull request merged**
