### PR TITLE
Config dataclasses

### PR DESCRIPTION
**Pull request by AurelienJaquier**
- the subgroups of configuration data are no longer dictionaries, but dataclasses
- they are not created with functions in load module, but from methods in config class
- synapse mechanism data subgroup access is restricted to when add_synapses is True
- creation of get_rin_exp_voltage_base function in load, being called in create_hoc module

### CODE REVIEW

**Comment by AurelienJaquier** [comment]
I'm not sure preventing access to config data depending on the configuration is a very good idea. I was able to implement it for the synapse mechanism config data subgroup, but when we depend on some logic outside of emodelrunner, it can backfire. E.g. when we create a BPO sim object, we give it cvode_active and dt from config, because the logic to 'get the meaningful data' is in BPO. Therefore we cannot easily say 'if cvode_active is True, then prevent the access to dt'. The same goes with some data needed in the hoc creation (e.g. hoc_synapse_template_name that is needed even when we are not using synapses because that logic is in jinja files)

Overall I am not sure this MR adds a lot to EModelRunner. It complexifies the code (replaces instinctively understandable dicts with dataclasses) but does not add a lot of essential features.

What do you think @anilbey ?

**Comment by anilbey** [comment]
Thanks @AurelienJaquier, let me take the time to read the whole project's code and get back to this issue.

**Comment by anilbey** [comment]
In a quick glance,

> but when we depend on some logic outside of emodelrunner, it can backfire.|


I see, right we cannot do much to control the hoc.

This MR however has positive impact as well.

* It moves the config loading code to the configuration module.
* The dataclasses are annotating the types of the attributes.
* In our use case (AFAIK), these parameters are all read-only. We can make the dataclasses immutable with the `@dataclass(frozen=True)` to make sure no side effect changes the values that should not be modified.

**Comment by anilbey** [comment]
I think it's good to have an immutable data structure for storing the configuration data.

`namedtuple` or `dataclass` (frozen) are two good candidates for that. Unlike namedtuple, dataclass can also add logic (as you implemented in SynMechArgs) to prevent misuse.

**Comment by AurelienJaquier** [comment]
Alright! syn_mech_args are actually not read-only in get_postcell, but I can fix that.

**Review by anilbey — APPROVED** [review]
Thanks! Looks very good

**Pull request merged**
