### PR TITLE
add python 3.11 to the test suite

### PR DESCRIPTION
**Pull request by AurelienJaquier**

### CODE REVIEW

**Comment by AurelienJaquier** [comment]
Arf. NEURON has been released, but h5py and MorphIO have not yet py3.11 wheels.

**Comment by wvangeit** [comment]
Maybe you can ping them in tickets? (I guess h5py already has one)

**Comment by AurelienJaquier** [comment]
Alright, pinging https://github.com/h5py/h5py/issues/2146 for python 3.11 wheels
It looks like MorphIO is also discussing python 3.11 wheels in this ticket https://github.com/BlueBrain/MorphIO/issues/429 but they are also waiting on h5py for it.

**Review by anilbey — APPROVED** [review]
Looks good thanks

**Pull request merged**
