### PR TITLE
determine_package_type function that supports old configs without Pac…

### PR DESCRIPTION
**Pull request by anilbey**
…kage field

### CODE REVIEW

**Review by AurelienJaquier — APPROVED** [review]
great !

**Comment by anilbey** [comment]
I don't know why coverage drops, the unit test covers the function.

**Comment by AurelienJaquier** [comment]
It looks like there was an error in the upload to codecov. Maybe it is the reason the coverage dropped?

**Comment by AurelienJaquier** [comment]
You can see the error in test (whichever python version), and then on 'upload coverage to codecov'

**Comment by AurelienJaquier** [comment]
I re-launched the tests and codecov was uploaded without error, but the thalamus replace axon is still not covered

**Pull request merged**
