### PR TITLE
GUI tests

### PR DESCRIPTION
**Pull request by AurelienJaquier**
Some fixes in GUI simulator & new tests for GUI simulator's functions and class methods

### CODE REVIEW

**Comment by AurelienJaquier** [comment]
@anilbey I can make the tests pass, but I have to compile the mechanisms in tox in the current working directory, and not in the example directory (as is done for the other tests). Do you know the reason why?

**Comment by AurelienJaquier** [comment]
To run the GUI, you have to be in a directory containing a cell, e.g. examples/sscx_sample_dir/ However the inconsistency I pointed out is not with launching the GUI, but with the new tests of this PR.

**Comment by anilbey** [comment]
I also couldn't figure out what's wrong. It only happens in this function.

```
    def test_load_synapse_display_data(self):
        """Test load_synapse_display_data method."""
        with cwd(example_dir):
            self.simulator.load_cell_sim()
            self.simulator.cell.freeze(self.simulator.release_params)
            self.simulator.cell.instantiate(sim=self.simulator.sim)
```
I am not sure if that's due to a bug or not.

**Comment by anilbey** [comment]
I think it passed in your environment because you already had an `x86_64` folder created in the main directory.

**Comment by AurelienJaquier** [comment]
Yes, right.

**Review by anilbey — APPROVED** [review]
Brilliant!

**Pull request merged**
