### PR TITLE
Remove everything axon hoc related from synplas

### PR DESCRIPTION
**Pull request by AurelienJaquier**
* Removed replace_axon_hoc_path and templates_dir from config validator (default values and schema)
* Removed templates dir containing replace_axon_hoc.hoc from examples/synapse_sample

### CODE REVIEW

**Comment by anilbey** [comment]
Thanks @AurelienJaquier . This solves #32 right?

**Comment by anilbey** [comment]
There's also this parameter (`do_replace_axon`) in synplas. Is that one used?

https://github.com/BlueBrain/EModelRunner/pull/38/files#diff-1acb628dbf2be6fbe0d7565310369f197a04b30a44f727e93c6bdcd03b665bc1L403

```
        "Morphology": {
            "do_replace_axon": "True",
        },
```

**Comment by AurelienJaquier** [comment]
Yes, it does solve #32 .
do_replace_axon is used because we also replace the axon in synplas.
The axon hoc file is used when we create hoc files able to reproduce the python run. But EModelRunner is not designed to create these hoc files in synplas mode, so this is why we do not need the axon hoc file here.

**Review by anilbey — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
